Repository sysadminsmedia/homebox, pull requests merged in 2025-06, with the labels that each got.

#777 Abstract Attachment Storage
  Dockerfile
  Dockerfile.rootless
  Taskfile.yml
  backend/app/api/handlers/v1/v1_ctrl_items_attachments.go
  backend/app/api/main.go
  backend/app/api/static/docs/docs.go
  backend/app/api/static/docs/swagger.json
  backend/app/api/static/docs/swagger.yaml
  backend/go.mod
  backend/go.sum
  backend/internal/core/services/main_test.go
  backend/internal/core/services/service_items_attachments_test.go
  backend/internal/data/repo/main_test.go
  backend/internal/data/repo/repo_item_attachments.go
  backend/internal/data/repo/repos_all.go
  backend/internal/sys/config/conf_database.go
  docs/.vitepress/menus/en.mts
  docs/en/api/openapi-2.0.json
  docs/en/api/openapi-2.0.yaml
  docs/en/configure/index.md
  docs/en/configure/storage.md
  docs/en/installation.md
Labels: 📖 documentation, ⬆️ enhancement, go

#773 Prevent self-referencing locations and items as parents
  frontend/components/Item/Selector.vue
  frontend/components/Location/Selector.vue
  frontend/composables/use-location-helpers.ts
  frontend/pages/item/[id]/index/edit.vue
  frontend/pages/location/[id].vue
Labels: ⬆️ enhancement

#824 fix: foreign key issue with thumbnails
  Taskfile.yml
  backend/go.sum
  backend/internal/core/services/service_items_attachments.go
  backend/internal/data/migrations/postgres/20250629112901_fix_thumbnail_foriegn.sql
  backend/internal/data/migrations/sqlite3/20250629112902_fix_thumbnail_foriegn.sql
  backend/internal/data/repo/repo_item_attachments.go
  frontend/composables/use-location-helpers.ts
  frontend/pages/items.vue
Labels: 🕷️ bug
