Repository sysadminsmedia/homebox, pull requests merged in 2025-07, with the labels that each got.

#857 Use aspect ratio when making thumbnails
  backend/app/api/main.go
  backend/go.mod
  backend/go.sum
  backend/internal/data/repo/repo_item_attachments.go
  backend/internal/data/repo/repo_item_attachments_test.go
  backend/pkgs/utils/image.go
Labels: 🕷️ bug, ⬆️ enhancement, go

#870 Allow github actions on forks
  .github/workflows/docker-publish-rootless.yaml
  .github/workflows/docker-publish.yaml
Labels: ⬆️ enhancement

#879 fix(frontend/location): preserve parent location when using "Create and Add another"
  frontend/components/Location/CreateModal.vue
Labels: ⬆️ enhancement

#897 Refactor main file, add support for postgres certificate authentication
  backend/app/api/main.go
  backend/app/api/recurring.go
  backend/app/api/setup.go
  backend/internal/data/repo/repo_item_attachments_test.go
  backend/internal/sys/config/conf_database.go
  docs/en/configure/index.md
Labels: 📖 documentation, ⬆️ enhancement, go

#896 Daily Analytics
  backend/app/api/main.go
  backend/internal/sys/analytics/analytics.go
Labels: ⬆️ enhancement
